# Generated by Django 5.1.2 on 2025-02-12 13:55

import textwrap
import uuid

import django.core.validators
from django.db import migrations, models
from guardian.ctypes import get_content_type

from arches.app.models.fields.i18n import I18n_String

PLUGIN_ID = uuid.UUID("70aa3e80-4aea-4042-a76e-5a872b1c36a1")


class Migration(migrations.Migration):

    dependencies = [
        ("arches_rule_based_permissions", "0001_initial"),
    ]

    def add_plugin(apps, schema_editor):
        Plugin = apps.get_model("models", "Plugin")

        Plugin(
            pluginid=PLUGIN_ID,
            name=I18n_String("Permission Rule Manager"),
            icon="fa fa-shield",
            component="views/components/plugins/rule-config-manager",
            componentname="rule-config-manager",
            config={"show": True},
            slug="rule-config-manager",
            sortorder=0,
        ).save()

    def remove_plugin(apps, schema_editor):
        Plugin = apps.get_model("models", "Plugin")
        Plugin.objects.filter(slug="rule-config-manager").delete()

    operations = [
        migrations.RunPython(add_plugin, remove_plugin),
    ]