# Generated by Django 6.0.5 on 2026-07-04 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arches_rule_based_permissions', '0002_rule_manager'),
        ('models', 'v820_0001_add_data_migrations_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleconfig',
            name='node',
            field=models.ForeignKey(blank=True, db_column='nodeid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.node'),
        ),
        migrations.AlterField(
            model_name='ruleconfig',
            name='nodegroup',
            field=models.ForeignKey(blank=True, db_column='nodegroupid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.nodegroup'),
        ),
    ]
